name: Run Pipelines and Commit Results

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths-ignore:
      - 'results/**'

permissions:
  contents: write

jobs:
  run-pipelines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn gensim

      - name: Run pipelines (generate CSV)
        run: |
          python main.py

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-results
          path: results/pipeline_results.csv
          if-no-files-found: error

      - name: Commit and push CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(results): update pipeline results [skip ci]"
          file_pattern: results/pipeline_results.csv
